---
- block:
    - name: redirect 80 to 8080
      ansible.builtin.iptables:
        table: nat
        chain: PREROUTING
        in_interface: "{{ ansible_default_ipv4.interface }}"
        protocol: tcp
        match: tcp
        destination_port: 80
        jump: REDIRECT
        to_ports: 8080
        comment: redirect 80 to 8080

    - name: save rule in file
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

    - name: install iptables-persistent
      ansible.builtin.apt:
        state: present
        name: iptables-persistent

  become: true
  when: ansible_distribution == 'Debian'
